# Generated by Django 4.1.4 on 2022-12-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('phone', models.IntegerField()),
                ('psw', models.CharField(max_length=20)),
            ],
        ),
    ]
